// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwQdKlqDxqVUlRvs7NU7QLStlXYobEl9k',
    appId: '1:255436758089:web:515860c1a03a39d7b07398',
    messagingSenderId: '255436758089',
    projectId: 'qr-delight-cca5d',
    authDomain: 'qr-delight-cca5d.firebaseapp.com',
    storageBucket: 'qr-delight-cca5d.appspot.com',
    measurementId: 'G-KJQW3FWMHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeIGlXGNBCeepZkXs7E901mqs_Rs9IRjY',
    appId: '1:255436758089:android:cdf1071ae8d39b60b07398',
    messagingSenderId: '255436758089',
    projectId: 'qr-delight-cca5d',
    storageBucket: 'qr-delight-cca5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0tDcKZcz14IkvrjAwFMvQOPNVjFtU9Tc',
    appId: '1:255436758089:ios:b76220ac7eb515eab07398',
    messagingSenderId: '255436758089',
    projectId: 'qr-delight-cca5d',
    storageBucket: 'qr-delight-cca5d.appspot.com',
    iosBundleId: 'com.example.qrDelight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0tDcKZcz14IkvrjAwFMvQOPNVjFtU9Tc',
    appId: '1:255436758089:ios:dd059db974364439b07398',
    messagingSenderId: '255436758089',
    projectId: 'qr-delight-cca5d',
    storageBucket: 'qr-delight-cca5d.appspot.com',
    iosBundleId: 'com.example.qrDelight.RunnerTests',
  );
}
